// src/web/app-vue/src/components/FileInput.vue
<template>
  <div class="file-input">
    <input
      type="file"
      accept=".wav"
      style="display: none"
      ref="fileInput"
      @change="handleFileChange"
    />
    <button
      @click="fileInput?.click()"
      :disabled="loading"
      class="select-button"
    >
      {{ loading ? 'ロード中...' : 'WAVファイルを選択' }}
    </button>
    <p v-if="fileName" class="file-name">
      選択されたファイル: {{ fileName }}
    </p>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { loadWavFile, downsampleAudio } from '../../../shared/audioUtils'
import { prepareAudioData } from '../../../shared/fft'
import type { ComplexNumber } from '../../../shared/types'

const emit = defineEmits<{
  (e: 'dataLoaded', data: ComplexNumber[]): void
}>()

const fileName = ref('')
const loading = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

const handleFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  if (!file) return

  try {
    loading.value = true
    fileName.value = file.name
    
    // WAVファイルを読み込み
    const audioData = await loadWavFile(file)
    
    // 2048サンプルにダウンサンプリング（2^11）
    const downsampledData = downsampleAudio(audioData, 2048)
    
    // FFT用の複素数データに変換
    const complexData = prepareAudioData(downsampledData)
    
    emit('dataLoaded', complexData)
  } catch (error) {
    console.error('ファイル処理エラー:', error)
    if (error instanceof Error) {
      alert(error.message)
    }
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.file-input {
  margin: 1rem;
}

.select-button {
  padding: 0.5rem 1rem;
  background-color: #42b883;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.select-button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

.file-name {
  margin-top: 0.5rem;
  color: #666;
}
</style>

// src/web/app-react/src/components/FileInput.js
import React, { useState } from 'react';
import { Button, Box, Typography } from '@mui/material';
import { loadWavFile, downsampleAudio } from '../../../shared/audioUtils';
import { prepareAudioData } from '../../../shared/fft';

const FileInput = ({ onDataLoad }) => {
  const [fileName, setFileName] = useState('');
  const [loading, setLoading] = useState(false);

  const handleFileChange = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    try {
      setLoading(true);
      setFileName(file.name);
      
      // WAVファイルを読み込み
      const audioData = await loadWavFile(file);
      
      // 2048サンプルにダウンサンプリング（2^11）
      const downsampledData = downsampleAudio(audioData, 2048);
      
      // FFT用の複素数データに変換
      const complexData = prepareAudioData(downsampledData);
      
      onDataLoad(complexData);
    } catch (error) {
      console.error('ファイル処理エラー:', error);
      alert(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box sx={{ m: 2 }}>
      <input
        accept=".wav"
        style={{ display: 'none' }}
        id="wav-file-input"
        type="file"
        onChange={handleFileChange}
      />
      <label htmlFor="wav-file-input">
        <Button
          variant="contained"
          component="span"
          disabled={loading}
        >
          {loading ? 'ロード中...' : 'WAVファイルを選択'}
        </Button>
      </label>
      {fileName && (
        <Typography variant="body1" sx={{ mt: 1 }}>
          選択されたファイル: {fileName}
        </Typography>
      )}
    </Box>
  );
};

export default FileInput;
